# -*- coding: utf-8 -*-
"""sudoku_starter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkWUBXwJKc9NG38dDml-Sw_XT9JewElt

### Important instructions on how to run the notebook
- Copy/ upload the notebook in kaggle.
- Make sure you have verified your phone number and have internet access, else you will not be able to use GPUs
- Settings -> accelerator -> GPU P100
- You get 30 hours of free GPUs on Kaggle per week. If more is needed, create multiple google accounts : )
- For experimenting, run the notebook in draft session. (The one that will start running if you run any of the cells right now)
- - Incase you want to put multiple models on train in loop/ anything time taking, Save Version -> Version type - Save and run all -> Advanced Settings- Run with GPU for this session.
  - Note that you need to add code blocks to store whatever you ran(for example model weights/plots/csvs) in Output - kaggle/working. So that you can download them after the session is run.
  - https://www.kaggle.com/code/nicholasdunham/saving-and-persisting-data-in-kaggle
### Important notes
- There **might** be intentional mistakes
- Be creative, curious and think critically. We want to judge these skills and not just neat code. While that is important, LLMs can be used.
- We expect basic understanding of whatever code you submit. There will be minor but important hyper parameters and tricks, those should be yours -- not any LLMs.
- A general advice while learning is- even if you use LLMs, might be a good idea to not copy paste and type out yourself.
- Any new library being used, new functions -- while learning, it would be suggested to go and check the documentation and know more about it -- are there similar libraries which are better and easier to use? LLMs will basically choose heavily from the context you give and is by default limited. Self exploration is important before trusting LLMs. Else learning curve and satisfaction both are low.

- The block below is important or good luck fixing dependency issues
- - Note: it will just keep running for sometime without any output
  - Trust the process, eventually it will finish (give it some 3-4 mins)
"""

"""## Code snippet for training a Sudoku transformer
- For making changes in positional embeddings/ decoding strategies, define new classes for the same, use them in training.
- For running training across multiple models, for depth-breadth experiment, come up with experiment design - model architectures (# layers, #parameters, #parameters per layer etc.) you want to test across to be able to make conclusive results. Write code blocks for the same. Below is just starter script
- Might also be useful to take note of convergence of loss/ accuracy for example to know whether the experiment is sufficient and not limited due to lack of training.
- You are free to make any changes in any part of the transformer architecture. State your hypothesis and intution. You are also encouraged to report negative results in your application.
- Add appropriate comments and markdown notes in the notebook you submit.
- Feel free to refer to papers/ blogs / any existing literature for motivating your ideas.

### For Out of memory issues, if any, reduce batch size.

### If you get an error for torch compatiblity in the block below- stop session - start session
"""

import torch
import torch.nn as nn
import math
import os
#from tqdm import tqdm
import pandas as pd
from torch.utils.data import Dataset, DataLoader
import time
# ==========================================
# 1. DATASET DEFINITION
# ==========================================
class SudokuDataset(Dataset):
    def __init__(self, csv_file, max_samples=10000,start=0):
        """
        Loads the Kaggle Sudoku dataset.
        Columns expected: 'puzzle', 'solution' (81 character strings)
        """
        self.data = pd.read_csv(csv_file, nrows=max_samples,skiprows=range(1,start) if start !=0 else 0)
        self.vocab_size = 12 # 0=blank, 1-9=digits, 10=bos, 11=EOS
        self.bos_token = 10
        self.eos_token = 11

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        quiz_str = self.data.iloc[idx]['puzzle']
        sol_str = self.data.iloc[idx]['solution']

        # Convert strings to tensors. '0' maps to 0 (blank), '1'-'9' map to 1-9.
        quiz = torch.tensor([int(c) for c in quiz_str], dtype=torch.long)
        sol = torch.tensor([int(c) for c in sol_str], dtype=torch.long)
        return quiz, sol

# ==========================================
# 2. EMBEDDINGS
# ==========================================

class PositionalEncoding1D(nn.Module):
    """
    Standard 1D Sin/Cosine Positional Encoding.
    """
    def __init__(self, d_model, max_len=100):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe.unsqueeze(0)) # Shape: (1, max_len, d_model)

    def forward(self, x,y):
        # x shape: (batch_size, seq_len, d_model)
        return x + self.pe[:, :x.size(1), :]
    
class SudokuPositionalEmbedding(nn.Module):
    def __init__(self, d_model):
        super().__init__()

        self.row_embed = nn.Embedding(9, d_model)
        self.col_embed = nn.Embedding(9, d_model)
        self.box_embed = nn.Embedding(9, d_model)

        rows = []
        cols = []
        boxes = []

        for r in range(9):
            for c in range(9):
                rows.append(r)
                cols.append(c)
                boxes.append((r // 3) * 3 + (c // 3))

        self.register_buffer(
            "row_ids",
            torch.tensor(rows, dtype=torch.long)
        )

        self.register_buffer(
            "col_ids",
            torch.tensor(cols, dtype=torch.long)
        )

        self.register_buffer(
            "box_ids",
            torch.tensor(boxes, dtype=torch.long)
        )

    def forward(self, x, y=None):

        row = self.row_embed(self.row_ids).unsqueeze(0)
        col = self.col_embed(self.col_ids).unsqueeze(0)
        box = self.box_embed(self.box_ids).unsqueeze(0)

        return x + row + col + box

# ==========================================
# 3. MODEL ARCHITECTURE
# ==========================================

class SudokuTransformer(nn.Module):
    def __init__(self, vocab_size=12, d_model=128, nhead=4, num_layers=3):
        super().__init__()
        self.d_model = d_model

        self.token_embedding = nn.Embedding(vocab_size, d_model)
        if USE_SUDOKU_POSITIONAL:
            self.pos_encoder = SudokuPositionalEmbedding(d_model)
        else:
            self.pos_encoder = PositionalEncoding1D(d_model)

        self.transformer = nn.Transformer(
            d_model=d_model,
            nhead=nhead,
            num_encoder_layers=num_layers,
            num_decoder_layers=num_layers,
            dim_feedforward=d_model * 4,
            batch_first=True
        )
        self.fc_out = nn.Linear(d_model, vocab_size)

    def generate_square_subsequent_mask(self, sz, device):
        # Causal mask for autoregressive training
        mask = torch.triu(torch.ones(sz, sz) * float('-inf'), diagonal=1)
        return mask.to(device)

    def forward(self, src, tgt):
        # src: (batch, 81), tgt: (batch, seq_len)
        tgt_mask = self.generate_square_subsequent_mask(tgt.size(1), tgt.device)

        src_emb = self.pos_encoder(self.token_embedding(src) * math.sqrt(self.d_model),'src')
        tgt_emb = self.pos_encoder(self.token_embedding(tgt) * math.sqrt(self.d_model),'tgt')

        out = self.transformer(src_emb, tgt_emb, tgt_mask=tgt_mask)
        return self.fc_out(out)

# ==========================================
# 4. GENERATION
# ==========================================
def generate_autoregressive(model, src, max_len=81, bos_token=10, eos_token=11, device='cpu'):
    """
    Standard Left-to-Right Autoregressive Generation.
    """
    model.eval()
    src = src.unsqueeze(0).to(device) # Add batch dim
    tgt = torch.tensor([[bos_token]], dtype=torch.long).to(device)

    with torch.no_grad():
        for _ in range(max_len):
            outputs = model(src, tgt)
            next_token_logits = outputs[:, -1, :] # Get last token logits
            next_token = next_token_logits.argmax(dim=-1).unsqueeze(1)

            tgt = torch.cat([tgt, next_token], dim=1)
            if next_token.item() == eos_token:
                break

    return tgt.squeeze(0)[1:] # Remove bos token

# ==========================================
# 5. TRAINING LOOP
# ==========================================
t_a=[]
v_a=[]
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
USE_SUDOKU_POSITIONAL = True
# Experiment settings
batch_size = 128
configs = [
    (8, 64, 1e-3),
]
epochs = 50

dataset = SudokuDataset(
    'data/sudoku.csv',
    max_samples=50000
)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

val_set = SudokuDataset(
    'data/sudoku.csv',
    start=50000,
    max_samples=10000
)
val_loader = DataLoader(val_set, batch_size=batch_size)

criterion = nn.CrossEntropyLoss()
os.makedirs("results", exist_ok=True)
results = []

print("Data loaded")
def train(num_layers, d_model, lr):

    model = SudokuTransformer(
        vocab_size=dataset.vocab_size,
        d_model=d_model,
        num_layers=num_layers
    ).to(device)

    num_params = sum(p.numel() for p in model.parameters())

    print(f"Parameters: {num_params:,}")

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=lr
    )

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=epochs
    )

    experiment_start = time.perf_counter()

    best_val_acc = 0

    for epoch in range(epochs):
        start_time=time.perf_counter()
        model.train()
        total_loss = 0
        train_acc=0
        val_acc=0
        for src, target in dataloader:
            src, target = src.to(device), target.to(device)

            # Inputs to decoder: [bos, t_1, t_2, ..., t_80]
            # Expected outputs: [t_1, t_2, ..., t_81]
            bos_tensor = torch.full((target.size(0), 1), dataset.bos_token, dtype=torch.long, device=device)
            tgt_input = torch.cat([bos_tensor, target[:, :-1]], dim=1)

            optimizer.zero_grad()
            logits = model(src, tgt_input)
            train_acc+=(logits.reshape(-1,dataset.vocab_size).argmax(dim=1) == target.reshape(-1)).float().mean().item()

            # Reshape for CrossEntropy: (batch * seq_len, vocab_size)
            loss = criterion(logits.reshape(-1, dataset.vocab_size), target.reshape(-1))
            loss.backward()
            optimizer.step()


            total_loss += loss.item()
        model.eval()
        with torch.no_grad():
            for src,target in val_loader:
                src, target = src.to(device), target.to(device)
                bos_tensor = torch.full((target.size(0), 1), dataset.bos_token, dtype=torch.long, device=device)
                tgt_input = torch.cat([bos_tensor, target[:, :-1]], dim=1)
                logits = model(src, tgt_input)
                val_acc+=(logits.reshape(-1,dataset.vocab_size).argmax(dim=1) == target.reshape(-1)).float().mean().item()

        current_val_acc = val_acc / len(val_loader)

        if current_val_acc > best_val_acc:
            best_val_acc = current_val_acc

            torch.save(
                model.state_dict(),
                f"results/BEST_L{num_layers}_D{d_model}_LR{lr}.pth"
            )
        
        scheduler.step()
        torch.cuda.empty_cache()
        end_time=time.perf_counter()
        time_delta=end_time-start_time
        time_r=time_delta*(epochs-1-epoch)
        time_m=time_r//60
        time_s=time_r-60*time_m
        t_a.append(train_acc/len(dataloader))
        v_a.append(val_acc/len(val_loader))
        print(f"Epoch {epoch+1} | Loss: {total_loss/len(dataloader):.4f} | Train acc: {train_acc/len(dataloader):.4f} | Val acc: {val_acc/len(val_loader):.4f} | Time remaining {time_m} min {time_s:.1f} s")
    model.eval()

    print("\nTraining complete.")

    runtime = time.perf_counter() - experiment_start

    results.append({
        "layers": num_layers,
        "parameters": num_params,
        "epochs": epochs,
        "d_model": d_model,
        "learning_rate": lr,
        "train_acc": train_acc / len(dataloader),
        "val_acc": val_acc / len(val_loader),
        "best_val_acc": best_val_acc,
        "loss": total_loss / len(dataloader),
        "runtime_sec": runtime,
    })

    torch.save(
        model.state_dict(),
        f"results/model_L{num_layers}_D{d_model}_LR{lr}.pth"
    )

if __name__ == "__main__":

    print("\nPOSITIONAL ENCODING:")
    print(
        "Sudoku Row+Column+Box"
        if USE_SUDOKU_POSITIONAL
        else "Standard Sinusoidal 1D"
    )

    for num_layers, d_model, lr in configs:

        print("\n" + "="*70)
        print(
            f"LAYERS={num_layers} | "
            f"D_MODEL={d_model} | "
            f"LR={lr}"
        )
        print("="*70)

        train(num_layers, d_model, lr)

    results_df = pd.DataFrame(results)

    print("\nFinal Results")
    print(results_df)

    filename = (
        "sudoku_positional_results.csv"
        if USE_SUDOKU_POSITIONAL
        else "standard_positional_results.csv"
    )

    results_df.to_csv(
        f"results/{filename}",
        index=False
    )